name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'octopus/**'
      - 'tests/**'
      - 'ci/**'
      - '.github/workflows/**'
      - 'pyproject.toml'
      - 'requirements*.txt'

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml@feat-dsl-config
